### PR TITLE
Split and continue node#4

### PR DESCRIPTION
**Pull request by skraatz**
Continue Node works

### CODE REVIEW

**Comment by gypsephi** [comment]
In FlowGraph_impl.hh, line 360: Please reset **count** to 0 instead to **num**. Then increase count by 1 for every promise you get und just **instantiate** a task when **count** equals **num**. 
Additionally, adapt the initialisation and the _registerPredecessor_ function.

This might avoid strange behaviour when connection nodes lately.

**Comment by gypsephi** [comment]
ContinueInput::pushPromise might be called asynchronously.
Please ensure mutal exclusion (use mutex, see JoinInput::tryJoinTask for reference).

**Comment by gypsephi** [comment]
SplitNode does not match my well (un)defined requirements.
It should be quite similar to the SplitNode in intel tbb (https://www.threadingbuildingblocks.org/docs/help/reference/flow_graph/split_node_cls.html).
A split node does not have user-defined body. It is templatized by its input tuple.
Its Sender ports equal the number and types given in the input tuple template parameter.
Whenever a promise with a input tuple is received, a split task should be spawned.
The body of this task should only split up the tuple and send each tuple element to the appropriate Sender.

**Comment by skraatz** [comment]
> In FlowGraph_impl.hh, line 360: Please reset **count** to 0 instead to **num**. Then increase count by 1 for every promise you get und just **instantiate** a task when **count** equals **num**.
> Additionally, adapt the initialisation and the _registerPredecessor_ function.
> 
> This might avoid strange behaviour when connection nodes lately.

done

**Comment by skraatz** [comment]
> ContinueInput::pushPromise might be called asynchronously.
> Please ensure mutal exclusion (use mutex, see JoinInput::tryJoinTask for reference).

done

**Pull request closed without merging**
